WijayanthaHardware/Models/PaintViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WijayanthaHardware.Models
{
    public class PaintViewModel
    {
        [Display(Name = "Paint Category")]
        public int PaintCategoryId { get; set; }
        public SelectList PaintCatergoryList { get; set; }
        [Display(Name = "Paint")]
        public int PaintSubCategoryId { get; set; }
        public SelectList PaintSubategoryList { get; set; }
        public string PaintColour { get; set; }
        public string Volume { get; set; }
        public int AvailableQuantity { get; set; }
        public double Price { get; set; }
        public string SubCategoryName { get; set; }
        public string CategoryName { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public int PaintId { get; set; }
        public string CostCode { get; set; }
        public SelectList Volumes { get; set; }
        public int VolumeId { get; set; }
        public int Quantity { get; set; }
        public int ColourId { get; set; }
        public string Colour { get; set; }
        public int PaintMasterId { get; set; }

    }
}

WijayanthaHardware/Controllers/PaintsController.cs
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WijayanthaHardware.BusinessObjects;
using WijayanthaHardware.Common;
using WijayanthaHardware.Models;
using WijayanthaHardware.Services;

namespace WijayanthaHardware.Controllers
{
    [Authorize]
    public class PaintsController : Controller
    {
        private readonly PaintService _paintService;
        private readonly LookUpServices _lookUpServices;

        public PaintsController(PaintService paintService, LookUpServices lookUpServices)
        {
            _paintService = paintService;
            _lookUpServices = lookUpServices;
        }

        public ActionResult Index()
        {
            var result = _lookUpServices.GetLookUp(LookUpTypeEnum.PaintCategory);
            var paintViewModel = new PaintViewModel
            {
                PaintCatergoryList = new SelectList(result, "LookUpId", "Value"),
                PaintSubategoryList = new SelectList(new List<LookUpBO>(), "LookUpId", "Value")
            };
            return View(paintViewModel);
        }

        public async Task<ActionResult> GetPaintSubCategory(int? paintCategoryId)
        {
            var result = await _paintService.GetPaintSubCategories(paintCategoryId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        public async Task<ActionResult> GetPaintColourLookup(string query)
        {
            var result = await _paintService.GetPaintColoursAsync(query);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> GetListOfPaintsByColour(int? PaintCategoryId, int? PaintSubCategoryId, int paintColourId)
        {
            var result = await _paintService.GetpaintByColourIdAsync(PaintCategoryId, PaintSubCategoryId, paintColourId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> AddNewPaintCategory(PaintViewModel paintViewModel)
        {
            var isSuccess = await _paintService.AddNewPaintCategoryAsync(paintViewModel);
            return isSuccess ? Json(new { status = TransactionStatusEnum.success.ToString(), title = "Success", message = "Paint Category has been saved successfully" }, JsonRequestBehavior.AllowGet)
                : Json(new { status = TransactionStatusEnum.error.ToString(), title = "Failed", message = "This Paint Category is already available" }, JsonRequestBehavior.AllowGet);
        }

        public async Task<PartialViewResult> EditPaint(int paintId)
        {
            var result = await _paintService.EditPaint(paintId);
            return PartialView("_EditPaint", result);
        }

        [HttpPost]
        public async Task<ActionResult> EditPaint(PaintViewModel paintViewModel)
        {
            await _paintService.UpdatePaintAsync(paintViewModel);
            return Json(new { status = TransactionStatusEnum.success.ToString(), title = "Success", message = "Paint details have been updated successfully" }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult AddPaint()
        {
            var paintViewModel = new PaintViewModel
            {
                Volumes = new SelectList(_lookUpServices.GetLookUp(LookUpTypeEnum.PaintVolume), "LookUpId", "Value"),
                PaintCatergoryList = new SelectList(_lookUpServices.GetLookUp(LookUpTypeEnum.PaintCategory), "LookUpId", "Value"),
                PaintSubategoryList = new SelectList(new List<LookUpBO>(), "LookUpId", "Value")
            };
            return View(paintViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> AddNewPaints(List<PaintViewModel> newPaintDetails)
        {
            var result = await _paintService.AddNewpaintsAsync(newPaintDetails);
            return result != string.Empty ? Json(new { status = TransactionStatusEnum.error.ToString(), title = "Failed", message = result }, JsonRequestBehavior.AllowGet) : Json(new { status = TransactionStatusEnum.success.ToString(), title = "Success", message = "Paints have been saved successfully" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> AddNewColour(string code, string colour)
        {
            var result = await _paintService.AddNewColourAsync(code, colour);
            return result ? Json(new { status = TransactionStatusEnum.error.ToString(), title = "Failed", message = "This colour is already added" }, JsonRequestBehavior.AllowGet) : Json(new { status = TransactionStatusEnum.success.ToString(), title = "Success", message = "New colour has been added successfully" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddCategory()
        {
            return View();
        }
    }
}

WijayanthaHardware/Views/Paints/AddCategory.cshtml
@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<div class="all-categories">
    <div class="container">
        <h2 class="big-heading">Categories</h2>
        <a class="same-btn pull-right" data-toggle="modal" href="#addcategory">Add new</a>
        <table class="paint-categories">
            <thead>
                <tr>
                    <th>Categories</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Category111</td>
                    <td>
                        <ul>
                            <li><a class="view-list" href="#"><i class="fas fa-list-ul"></i></a></li>
                            <li><a class="edit-category" href="#"><i class="fas fa-edit"></i></a></li>
                            <li><a class="delete-category" href="#"><i class="fas fa-trash"></i></a></li>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>Category111</td>
                    <td>
                        <ul>
                            <li><a class="view-list" href="#"><i class="fas fa-list-ul"></i></a></li>
                            <li><a class="edit-category" href="#"><i class="fas fa-edit"></i></a></li>
                            <li><a class="delete-category" href="#"><i class="fas fa-trash"></i></a></li>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>Category111</td>
                    <td>
                        <ul>
                            <li><a class="view-list" href="#"><i class="fas fa-list-ul"></i></a></li>
                            <li><a class="edit-category" href="#"><i class="fas fa-edit"></i></a></li>
                            <li><a class="delete-category" href="#"><i class="fas fa-trash"></i></a></li>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>Category111</td>
                    <td>
                        <ul>
                            <li><a class="view-list" href="#"><i class="fas fa-list-ul"></i></a></li>
                            <li><a class="edit-category" href="#"><i class="fas fa-edit"></i></a></li>
                            <li><a class="delete-category" href="#"><i class="fas fa-trash"></i></a></li>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>Category111</td>
                    <td>
                        <ul>
                            <li><a class="view-list" href="#"><i class="fas fa-list-ul"></i></a></li>
                            <li><a class="edit-category" href="#"><i class="fas fa-edit"></i></a></li>
                            <li><a class="delete-category" href="#"><i class="fas fa-trash"></i></a></li>
                        </ul>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@Html.Partial("_NewCategory")

WijayanthaHardware/Views/Paints/AddPaint.cshtml
@model WijayanthaHardware.Models.PaintViewModel
@{
    int counter = 0;
    ViewBag.Title = "AddPaint";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}
@section style{
    
    @Styles.Render("~/add-paint-css")
}
<div class="paint-master">
    <div class="container">
        <div class="paint-add-btns">
            <ul>
                <li><a class="same-btn" href="/Paints/AddCategory">Add category</a></li>
                <li><a class="same-btn" href="#addcolor" data-toggle="modal">Add color</a></li>
            </ul>
        </div>
        <div class="add-paint">
            <h1 class="big-heading">Add paint</h1>
            @using (Ajax.BeginForm("AddNewPaints", "Paints", null, new AjaxOptions { HttpMethod = "POST" }, new { @id = "AddPaints", role = "form" }))
            {
                <div class="row">
                    <div class="col-xs-12 col-md-6">
                        @Html.LabelFor(x => x.PaintCategoryId, new { @class = "small-heading" })
                        @Html.DropDownListFor(x => x.PaintCategoryId, Model.PaintCatergoryList, "Select Paint Category", new { @class = "wide" })
                    </div>
                    <div class="col-xs-12 col-md-6">
                        @Html.LabelFor(x => x.PaintSubCategoryId, new { @class = "small-heading" })
                        @Html.DropDownListFor(x => x.PaintSubCategoryId, Model.PaintSubategoryList, "Select Paint", new { @class = "wide" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-md-12">
                        <div id="paintSearch" class="search-bar common-margin">
                            <input id="searchBar" type="text" placeholder="Search Paint Color" class="typeahead">
                        </div>
                    </div>
                </div>

                foreach (var paintVolume in Model.Volumes)
                {
                    <div class="row itemlist" id="@paintVolume.Value" value="">
                        <div class="add-paint-quantity">
                            <div class="col-xs-6 col-sm-3 col-md-3 common-margin">
                                <input id="litre-@counter" type="checkbox" name="litre" value="@paintVolume.Value" />
                                <label for="litre-@counter">@paintVolume.Text</label>
                            </div>
                            <div class="col-xs-6 col-sm-3 col-md-3 common-margin">
                                <input type="text" name="Cost" value="" placeholder="Cost" disabled autocomplete="off" />
                            </div>
                            <div class="col-xs-6 col-sm-3 col-md-3 common-margin">
                                <input type="number" name="Price" value="" placeholder="Price" disabled min="0" class="form-control" autocomplete="off" />
                            </div>
                            <div class="col-xs-6 col-sm-3 col-md-3 common-margin">
                                <input type="number" name="Quantity" value="" placeholder="Quantity" disabled min="0" class="form-control" autocomplete="off" />
                            </div>
                        </div>
                    </div>
                    counter++;
                }
                <div class="row">
                    <div class="btns common-margin">
                        <button class="same-btn" type="submit">Save</button>
                        <button class="same-btn" type="reset">reset</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@*add paint modal*@

@Html.Partial("_AddColor", Model)

@*add paint modal end*@
@section script
{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @Scripts.Render("~/add-paint-js")

}

WijayanthaHardware/Views/Paints/Index.cshtml
@model WijayanthaHardware.Models.PaintViewModel
@{
    ViewBag.Title = "Paints";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}
@section style{
    @Styles.Render("~/paint-css")
}
<div class="page-content">
    <div class="container">
        <h1 class="big-heading">Paints</h1>
        <div class="row">
            <div class="col-xs-12 col-md-6">
                <div class="select-bar">
                    @Html.LabelFor(x => x.PaintCategoryId, new { @class = "small-heading" })
                    @Html.DropDownListFor(x => x.PaintCategoryId, Model.PaintCatergoryList, "Select Paint Category", new { @class = "wide select-list paint-list" })
                </div>
            </div>
            <div class="col-xs-12 col-md-6">
                <div class="select-bar">
                    @Html.LabelFor(x => x.PaintSubCategoryId, new { @class = "small-heading" })
                    @Html.DropDownListFor(x => x.PaintSubCategoryId, Model.PaintSubategoryList, "Select Paint", new { @class = "wide select-list paint-list" })
                </div>
            </div>
        </div>
        <div id="paintDetails">
            <table class="paint-details" id="paint-details-Table">
                <thead>
                    <tr>
                        <th>Colour</th>
                        <th>Volume</th>
                        <th>Quantity</th>
                        <th>Price</th>               
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
            <div id="markup"></div>
        </div>
    </div>
</div>
@section script
{
    @Scripts.Render("~/paint-js")
}

WijayanthaHardware/Views/Paints/_AddColor.cshtml
@model WijayanthaHardware.Models.PaintViewModel
<div class="modal fade" id="addcolor" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title small-heading" id="exampleModalLongTitle">Add New Color</h5>
            </div>
            @using (Ajax.BeginForm("AddNewColour", "Paints", null, new AjaxOptions { HttpMethod = "POST" }, new { @id = "AddNewColourForm", role = "form" }))
            {
                <div class="modal-body">
                    <label class="form-label">Color code</label><br />
                    <input id="newColourCode" type="text" name="name" value="" placeholder="Add color code" autocomplete="off"/>
                    <label class="form-label">Color name</label><br />
                    <input id="newColour" type="text" name="name" value="" placeholder="Add paint colour" autocomplete="off"/>
                    <label class="form-label">Color name</label><br />
                    <input id="newColour" type="text" name="name" value="" placeholder="Add paint colour" autocomplete="off"/>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="same-btn" >Save Changes</button>
                    <button type="button" class="same-btn" data-dismiss="modal">Close</button>
                </div>
            }
        </div>
    </div>
</div>

WijayanthaHardware/Views/Paints/_EditPaint.cshtml
@model WijayanthaHardware.Models.PaintViewModel

<div id="innerFormModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title small-heading">@Model.Colour</h5>
            </div>
            @using (Ajax.BeginForm("EditPaint", "Paints", null, new AjaxOptions { HttpMethod = "POST" }, new { @id = "EditPaint", role = "form" }))
            {
                @Html.HiddenFor(x => x.PaintMasterId)
                <div class="modal-body">
                    <label class="form-label">Update Quantity</label><br />
                    @Html.TextBoxFor(x => x.AvailableQuantity, null, new { type = "number", autocomplete = "off" })
                    <label class="form-label">Update Price</label><br />
                    @Html.TextBoxFor(x => x.Price, null, new { type = "number", autocomplete = "off" })
                </div>
                <div class="modal-footer">
                    <button type="submit" class="same-btn">Update</button>
                    <button type="button" class="same-btn" data-dismiss="modal">Close</button>
                </div>
            }
        </div>
    </div>
</div>

<script>
    $("#EditPaint").submit(function (event) {
        event.preventDefault();
        event.stopImmediatePropagation();
        showWaitBlock();

        var action = $("#EditPaint").attr("action");
        var dataString;
        dataString = new FormData($("#EditPaint").get(0));
        contentType = false;
        processData = false;
        $.ajax({
            type: "POST",
            url: "/Paints/EditPaint",
            data: dataString,
            dataType: "json",
            contentType: contentType,
            processData: processData,
            success: function (result) {
                hideWaitBlock();
                $('#innerFormModal').modal('hide');
                showToastr(result);
            },
            error: function (jqXHR, textStatus, errorThrown) {
                hideWaitBlock();
                toastr.error("Something went wrong, please try refreshing the page", "Failed");
                return;
            }
        });
    });

    $('#innerFormModal').on('hidden.bs.modal', function () {


        $.get("/Paints/GetListOfPaintsByColour?PaintCategoryId=" + $('#PaintCategoryId').val() + '&PaintSubCategoryId=' + $('#PaintSubCategoryId').val() + '&paintColourId=' + 0, function (data) {
            PaintTable.clear();
            PaintTable.rows.add(data);
            PaintTable.draw();
        });
    })

</script>

WijayanthaHardware/Views/Paints/_NewCategory.cshtml
<div class="modal fade" id="addcategory" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title small-heading" id="exampleModalLongTitle">New Category</h5>
            </div>
                <div class="modal-body">
                    <label class="form-label">Category Name</label><br />
                    <input type="text" name="name" value="" placeholder="Add new category" autocomplete="off" />
                    <label class="form-label">Category Description</label><br />
                    <textarea></textarea>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="same-btn">Save Changes</button>
                    <button type="button" class="same-btn" data-dismiss="modal">Close</button>
                </div>
        </div>
    </div>
</div>