WijayanthaHardware/Models/PowerToolsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WijayanthaHardware.Models
{
    public class PowerToolsViewModel
    {
        [Display(Name = "Tool Category")]
        public int PowerToolId { get; set; }
        public SelectList PowerToolSelectList { get; set; }
        [Display(Name = "Tool")]
        public int? PowerToolSubCategoryId { get; set; }
        public SelectList PowerToolSubSelectList { get; set; }
        public string ToolName { get; set; }
        public double ToolPrice { get; set; }
        public string ToolBrand { get; set; }
        public string WarrantyPeriod { get; set; }
        public string CostCode { get; set; }
        public int AvailableQuantity { get; set; }
        public string Details { get; set; }
        public int PowerToolMasterId { get; set; }
    }
}

WijayanthaHardware/Controllers/PowerToolsController.cs
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WijayanthaHardware.BusinessObjects;
using WijayanthaHardware.Common;
using WijayanthaHardware.Models;
using WijayanthaHardware.Services;

namespace WijayanthaHardware.Controllers
{
    [Authorize]
    public class PowerToolsController : Controller
    {
        private readonly LookUpServices _lookUpServices;
        private readonly PowerToolService _powerToolService;

        public PowerToolsController(LookUpServices lookUpServices, PowerToolService powerToolService)
        {
            _lookUpServices = lookUpServices;
            _powerToolService = powerToolService;
        }

        public ActionResult Index()
        {
            var lookUpCategory = _lookUpServices.GetLookUp(LookUpTypeEnum.PowerToolCategory);
            var powerToolViewModel = new PowerToolsViewModel
            {
                PowerToolSelectList = new SelectList(lookUpCategory, "LookUpId", "Value"),
                PowerToolSubSelectList = new SelectList(new List<LookUpBO>(), "LookUpId", "Value")
            };
            return View(powerToolViewModel);
        }

        public async Task<ActionResult> GetPowerToolSubCategories(int? powerToolCategory)
        {
            var result = await _powerToolService.GetPowerToolsSubCategory(powerToolCategory);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> GetPowerToolSubCategoryDetail(int? powerToolSubCatId, int? powerToolCategory)
        {
            var result = await _powerToolService.GetPowerToolSubCategoryDetailAsync(powerToolSubCatId, powerToolCategory);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public async Task<PartialViewResult> EditPowerTool(int PowerToolId)
        {
            var result = await _powerToolService.EditPowerTool(PowerToolId);
            return PartialView("_EditPowerTool", result);
        }

        [HttpPost]
        public async Task<ActionResult> EditPowerTool(PowerToolsViewModel powerToolsViewModel)
        {
            await _powerToolService.UpdatePaintAsync(powerToolsViewModel);
            return Json(new { status = TransactionStatusEnum.success.ToString(), title = "Success", message = "Paint details have been updated successfully" }, JsonRequestBehavior.AllowGet);
        }

    }
}

WijayanthaHardware/Views/PowerTools/Index.cshtml
@model WijayanthaHardware.Models.PowerToolsViewModel
@{
    ViewBag.Title = "Power Tools";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}
@section style{
    @Styles.Render("~/powertool-css")
}
<div class="page-content">
    <div class="container">
        <h1 class="big-heading">power tools</h1>
        <div class="row">
            @*<a href="#pwredit" data-toggle="modal" class="same-btn pull-right">Edit</a>
            <a class="btn-load-inner-form-modal-edit" href="@Url.Action("EditPowerTool", "PowerTools", new { PowerToolId = Model.PowerToolMasterId })">Hello</a>*@
        </div>
        <div class="row">
            <div class="col-xs-12 col-md-6">
                <div class="select-bar">
                    @Html.LabelFor(x => x.PowerToolId, new { @class = "small-heading" })
                    @Html.DropDownListFor(x => x.PowerToolId, Model.PowerToolSelectList, "Select Tool Category", new { @class = "wide select-list" })
                </div>
            </div>
            <div class="col-xs-12 col-md-6">
                <div class="select-bar">
                    @Html.LabelFor(x => x.PowerToolSubCategoryId, new { @class = "small-heading" })
                    @Html.DropDownListFor(x => x.PowerToolSubCategoryId, Model.PowerToolSubSelectList, "Select Tool", new { @class = "wide select-list" })
                </div>
            </div>
        </div>
        <div class="item-details" id="item-details-Table" style="opacity:0;">
            <div class="row">
                <div class="col-xs-12 col-md-6">
                    <div class="item-left">
                        <div class="item-name" id="@Html.IdFor(x=>x.ToolName)"></div>
                        <table class="power-tools">
                            <tr>
                                <td>Price</td>
                                <td id="@Html.IdFor(x=>x.ToolPrice)"></td>
                            </tr>
                            <tr>
                                <td>Cost code</td>
                                <td id="@Html.IdFor(x=>x.CostCode)"></td>
                            </tr>
                            <tr>
                                <td>Detail</td>
                                <td id="@Html.IdFor(x=>x.Details)"></td>
                            </tr>
                            <tr>
                            <tr>
                                <td>Warranty Period</td>
                                <td id="@Html.IdFor(x=>x.WarrantyPeriod)"></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>
                                    @*<a id="pt-edit-link" class="btn-load-inner-form-modal-edit" href="">Hello</a>*@
                                    <a id="pt-edit-link" href="#pwredit" class="same-btn pull-right btn-load-inner-form-modal-edit">Edit</a>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="col-xs-12 col-md-6">
                    <div class="item-right">
                        <div class="availability-count" id="@Html.IdFor(x=>x.AvailableQuantity)"></div>
                        <div class="availability-text">Item(s) remaining</div>
                    </div>

                    
                </div>
            </div>
        </div>
    </div>
</div>

<div id="markup"></div>

@section script
{
    @Scripts.Render("~/powertool-js")
}

WijayanthaHardware/Views/PowerTools/_EditPowerTool.cshtml
@model WijayanthaHardware.Models.PowerToolsViewModel

<div id="innerFormModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title small-heading">Edit Tools</h5>
            </div>

            @using (Ajax.BeginForm("EditPowerTool", "Paints", null, new AjaxOptions { HttpMethod = "POST" }, new { @id = "EditPowerTool", role = "form" }))
            {
                @Html.HiddenFor(x => x.PowerToolMasterId)
                <div class="modal-body">
                    <label class="form-label">Update Quantity</label><br />
                    @Html.TextBoxFor(x => x.AvailableQuantity, null, new { type = "number", autocomplete = "off" })
                    <label class="form-label">Update Price</label><br />
                    @Html.TextBoxFor(x => x.ToolPrice, null, new { type = "number", autocomplete = "off" })
                </div>
                <div class="modal-footer">
                    <button type="submit" class="same-btn">Update</button>
                    <button type="button" class="same-btn" data-dismiss="modal">Close</button>
                </div>
            }
        </div>
    </div>
</div>
<script>
    $("#EditPowerTool").submit(function (event) {
        event.preventDefault();
        event.stopImmediatePropagation();
        showWaitBlock();

        var action = $("#EditPowerTool").attr("action");
        var dataString;
        dataString = new FormData($("#EditPowerTool").get(0));
        contentType = false;
        processData = false;
        $.ajax({
            type: "POST",
            url: "/PowerTools/EditPowerTool",
            data: dataString,
            dataType: "json",
            contentType: contentType,
            processData: processData,
            success: function (result) {
                hideWaitBlock();
                $('#innerFormModal').modal('hide');
                showToastr(result);
            },
            error: function (jqXHR, textStatus, errorThrown) {
                hideWaitBlock();
                toastr.error("Something went wrong, please try refreshing the page", "Failed");
                return;
            }
        });
    });

    //$('#innerFormModal').on('hidden.bs.modal', function () {


    //    $.get("/Powertools/GetListOfPowerToolsByDetails?PowerToolCategoryId=" + $('#PowerToolCategoryId').val() + '&PowerToolSubCategoryId=' + $('#PowerToolSubCategoryId').val() + '&Details=' + 0, function (data) {
    //        PaintTable.clear();
    //        PaintTable.rows.add(data);
    //        PaintTable.draw();
    //    });
    

</script>

WijayanthaHardware/Views/PowerTools/_editPowerTools.cshtml
@model WijayanthaHardware.Models.PowerToolsViewModel

<div id="innerFormModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title small-heading">@Model.Details</h5>
                </div>


                @using (Ajax.BeginForm("EditPowerTool", "PowerTool", null, new AjaxOptions { HttpMethod = "POST" }, new { @id = "EditPowerTool", role = "form" }))
                {
                    @Html.HiddenFor(x => x.PowerToolMasterId)
                    <div class="modal-body">
                        <label class="form-label">Update Quantity</label><br />
                        @Html.TextBoxFor(x => x.AvailableQuantity, null, new { type = "number", autocomplete = "off" })
                        <label class="form-label">Update Price</label><br />
                        @Html.TextBoxFor(x => x.ToolPrice, null, new { type = "number", autocomplete = "off" })
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="same-btn">Update</button>
                        <button type="button" class="same-btn" data-dismiss="modal">Close</button>
                    </div>
                }



            </div>
        </div>
    </div>


    <script>
        $("#EditPowerTool").submit(function (event) {
            event.preventDefault();
            event.stopImmediatePropagation();
            showWaitBlock();

            var action = $("#EditPowerTool").attr("action");
            var dataString;
            dataString = new FormData($("#EditPowerTool").get(0));
            contentType = false;
            processData = false;
            $.ajax({
                type: "POST",
                url: "/PowerTools/editPowerTools",
                data: dataString,
                dataType: "json",
                contentType: contentType,
                processData: processData,
                success: function (result) {
                    hideWaitBlock();
                    $('#innerFormModal').modal('hide');
                    showToastr(result);
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    hideWaitBlock();
                    toastr.error("Something went wrong, please try refreshing the page", "Failed");
                    return;
                }
            });
        });

        $('#pwredit').on('hidden.bs.modal', function () {
            $('#item-details-Table').animate({ opacity: 0 }, 85);
            $.ajax({
                type: "GET",
                url: "/PowerTools/GetPowerToolSubCategoryDetail?powerToolSubCatId=" + $(this).val() + "&powerToolCategory=" + $("#PowerToolId").val(),
                success: function (data) {
                    $('#item-details-Table').animate({ opacity: 1 }, 85);
                    $('#ToolName').text(data.ToolName);
                    $('#ToolPrice').text(data.ToolPrice + " LKR");
                    $('#Details').text(data.Details);
                    $('#WarrantyPeriod').text(data.WarrantyPeriod);
                    $('#CostCode').text(data.CostCode);
                    $('#AvailableQuantity').text(data.AvailableQuantity);
                }
            });
        });

        //$('#pwredit').on('hidden.bs.modal', function () {


        //   $.get("/PowerTool/GetListOfPaintsByColour?PaintCategoryId=" + $('#PaintCategoryId').val() + '&PaintSubCategoryId=' + $('#PaintSubCategoryId').val() + '&paintColourId=' + 0, function (data) {

        //        PaintTable.clear();
        //        PaintTable.rows.add(data);
        //        PaintTable.draw();
        //    });
        //})
</script>